version: '3.9'
services:
        front-end:
                build:
                  context: ./requirements/front-end
                  dockerfile: Dockerfile.prod
                image: front-end:v1
                container_name: front-end
                depends_on:
                        - back-end
                ports: 
                        - "80:80"
                restart: always
                networks:
                        - network

networks:
        network:
