version: '3.9'
services:
        frontend:
                build:
                  context: ./requirements/frontend
                  dockerfile: Dockerfile.prod
                image: frontend:v1
                container_name: frontend
                depends_on:
                        - backend
                ports: 
                        - "80:80"
                restart: always

        backend:
                build: 
                  context: ./requirements/backend
                  dockerfile: Dockerfile.prod
                image: backend:v1
                environment:
                        - RUN_ENV=${RUN_ENV}
                        - DB_HOSTNAME=${DB_HOSTNAME}
                        - DB_PORT=${DB_PORT}
                        - DB_NAME=${DB_NAME}
                        - DB_USER=${DB_USER}
                        - DB_PASS=${DB_PASS}
                        - DB_ROOT_PASS=${DB_ROOT_PASS}
                        - BACKEND_PORT=${BACKEND_PORT}
                container_name: backend
                depends_on:
                        - database
                ports: 
                        - "3000:3000"
                restart: always
                networks:
                        - database-network
        database:
                build:
                  context: ./requirements/database
                  args:
                        - DB_PORT=${DB_PORT}
                        - DB_NAME=${DB_NAME}
                        - DB_USER=${DB_USER}
                        - DB_PASS=${DB_PASS}
                        - DB_ROOT_PASS=${DB_ROOT_PASS}
                  dockerfile: Dockerfile.prod
                image: database:v1
                container_name: database
                restart: always
                volumes:
                  - db_vol:/var/lib/postgresql/data

volumes:
        db_vol:

networks:
        database-network:
          
