version: '3.9'
services:
        front-end:
                build:
                  context: ./requirements/front-end
                  dockerfile: Dockerfile.prod
                image: front-end:v1
                container_name: front-end
                depends_on:
                        - back-end
                ports: 
                        - "80:80"
                restart: always

        back-end:
                build:
                  context: ./requirements/back-end
                  dockerfile: Dockerfile.prod
                image: back-end:v1
                container_name: back-end
                depends_on:
                        - database
                ports: 
                        - "3000:3000"
                restart: always
                networks:
                        - database-network

networks:
        database-network:
