FROM node:alpine as builder

ENV NODE_ENV build

USER node

WORKDIR /home/node

COPY . /home/node

RUN yarn install && yarn build

# ---

FROM node:alpine

ENV NODE_ENV production

USER node
WORKDIR /app

COPY --from=builder /home/node/package*.json /app/
COPY --from=builder /home/node/node_modules/ /app/node_modules/
COPY --from=builder /home/node/dist/ /app/dist/

CMD ["node", "dist/main.js"]
