FROM node:17.6.0-slim as build

ARG REACT_APP_BACKEND_ADDRESS

ENV REACT_APP_BACKEND_ADDRESS $REACT_APP_BACKEND_ADDRESS

WORKDIR /build

COPY package.json .

COPY yarn.lock .

RUN yarn install

COPY . .

RUN yarn build

# PROD
FROM nginx:1.21.6

COPY ./nginx.conf /etc/nginx/nginx.conf

COPY --from=build /build/build /usr/share/nginx/html