import { ApiProperty, ApiPropertyOptional } from "@nestjs/swagger";

class Session2FaContentDTO {
    @ApiProperty({
        description: "Is 2FA activated or not"
    })
    needed: boolean;

    @ApiProperty({
        description: "Current state of 2FA verification"
    })
    passed: boolean;

    @ApiPropertyOptional({
        description: "Secret generated by OTP"
    })
    secret: string;
};

export class Session2FaDTO {
    @ApiProperty({
        description: "2FA container in session object",
        type: Session2FaContentDTO
    })
    twofa: Session2FaContentDTO
};