name: Deploy on production
on:
  push:
    branches: [ main ]

jobs:
  deploy-vps:
    name: Deploy cluster
    runs-on: ubuntu-latest
    steps:
      - name: setup ssh agent
        run: eval $(ssh-agent -s)
      - name: add ssh key
        run: ssh-add <(echo "${{ secrets.SSH_KEY }})
      - name: prepare ssh folder
        run: mkdir -p ~/.ssh
      - name: Allow fingerprint
        run: echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
      - name: deploy
      - run: ssh ${{ secrets.DEPLOY_LOGIN }}@${{ secrets.DEPLOY_HOST }}"cd ft_transcendence && docker-compose down -v && git pull && docker-compose up -d --build"

