name: Transcendence tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  front:
    name: Transcendence front end test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: NodeJS - environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: yarn install
        run: cd requirements/frontend && yarn install
      - name: yarn build
        run: cd requirements/frontend && yarn build
      - name: React - unit tests
        run: cd requirements/frontend && yarn test
  back:
    name: Transcendence back end test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: NodeJS - environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: yarn install
        run: cd requirements/backend && yarn install
      - name: yarn build
        run: cd requirements/backend && yarn build
      - name: React - unit tests
        run: cd requirements/backend && yarn test
